### ISSUE TITLE
Eunomo is causing issue with `Mix.Tasks.Format`

### ISSUE THREAD

**Issue by wilkinson4** [Roberto-XY/eunomo#15] opened 2022-10-18 22:28 UTC
We recently tried to implement the new version of Eunomo in our app and ran into issues with it causing ElixirLS to return `unable to fetch formatter_options` errors. There is something weird happening because when I tried to reproduce it in a small application what ended up happening when I hit my format keybinding in a file in my editor is that Eunomo would sort the alias, import, and require blocks, but then it wouldn't do the usual formatting afterward. I wrote a simple test that can be run in the Eunomo project as an example of the issue:

```elixir
defmodule FileTest do
  use ExUnit.Case

  test "sorts alias blocks, import blocks, require blocks, and also formats the file" do
    content = """
        defmodule Foo do
        alias Eunomo.Z.{L, I}
        alias Eunomo.Z

        def foo do
          1
        end
      end
    """

    IO.inspect(content, label: :content)

    assert :ok = File.write("foo.ex", content)

    {formatter, _opts} = Mix.Tasks.Format.formatter_for_file("foo.ex")

    {:ok, file} = File.read("foo.ex")

    formatted_string =
      formatter.(file) |> IO.iodata_to_binary() |> IO.inspect(label: :formatted_file)

    expected_result = """
      defmodule Foo do
        alias Eunomo.Z
        alias Eunomo.Z.{L, I}

        def foo do
          1
        end
      end
    """

    assert :ok = File.rm("foo.ex")

    IO.inspect(expected_result, label: :expected_result)
    formatted_properly? = String.equivalent?(formatted_string, expected_result)

    assert formatted_properly?
  end
end
```

My understanding is that this should sort the aliases alphabetically then also fix the indentation I added before the `defmodule` in `content`.

**Comment by Roberto-XY** [comment] 2022-10-21 10:00
Hi @wilkinson4 thanks for the report! I will look into it over the weekend.

**Comment by Roberto-XY** [comment] 2022-10-23 15:52
The issue is that the plugin system does not handle multiple formatters for the same extension. I did not notice that because it is not documented & I only tested the individual formatters. Unfortunate :(

v 1.14:
https://github.com/elixir-lang/elixir/blob/eb43a6a444c4aa9446ec1a7ad9801cedc897ab9d/lib/mix/lib/mix/tasks/format.ex#L511

```elixir
  defp find_formatter_for_file(file, formatter_opts) do
    ext = Path.extname(file)

    cond do
      plugin = find_plugin_for_extension(formatter_opts, ext) ->
        &plugin.format(&1, [extension: ext, file: file] ++ formatter_opts)

    # We never match here :(
      ext in ~w(.ex .exs) ->
        &elixir_format(&1, [file: file] ++ formatter_opts)

      true ->
        & &1
    end
  end
```

[In current main](https://github.com/elixir-lang/elixir/blob/b39f0e324edbf98808c72e6578ff2d3b751508fd/lib/mix/lib/mix/tasks/format.ex#L539) that already was partially fixed by allowing it for plugins. But still not in the combination with `.ex/s` files.

## What to do?

- Replace all three plugins with one plugin that also dispatches to the default Elixir formatter & passes opts along. Starting with Elixir 1.14.2 you should be able to split into 3 again (but have to run default formatter 3 times)— not good.
- Ask upstream about intention & possible fixes (e.g. treat the default formatter as something that _always_ runs before plugins)

For now, I would recommend staying with the previous release. I'll implement a fix in the coming week.

**Closed as completed** 2022-11-05 18:58 UTC

**Comment by Roberto-XY** [comment] 2022-11-05 19:18
Published new version that should fix the issue. Note the slightly different config format in `formatter.exs` to avoid formatting every file 3 times.

Let me know if there are any problems.

**Comment by wilkinson4** [comment] 2022-11-06 19:44
Nice! Thank you!
